### ISSUE TITLE
Zero points for LSST seem very faint

### ISSUE THREAD

**Issue by wadawson** [DarkEnergyScienceCollaboration/WeakLensingDeblending#1]
I was just going through [some of the code](https://github.com/DarkEnergyScienceCollaboration/WeakLensingDeblending/blob/master/descwl/survey.py#L181-202) and noticed that the zero points for LSST are set at:
- ZP_r = 55.8
- ZP_i = 41.5 

I did some quick calculations and get numbers around 30, which matches my expectations from using other telescopes like Subaru. I can copy some detailed calculations if it is helpful.

**Comment by mdschneider** [comment]
@wadawson I want to add zero points (and other needed quantities) for the remaining LSST bands in [this dict](https://github.com/DarkEnergyScienceCollaboration/WeakLensingDeblending/blob/master/descwl/survey.py#L177) in `survey.py`. Do you have a reference or calculation of recommended numbers for each band?

**Comment by dkirkby** [comment]
The zero points here are defined as the total detected signal rate in a specified pass band, in electrons per second, for a fiducial source with AB magnitude m0 = 24.  They are calculated from the tabulated filter curves as (taken from an appendix of the paper draft):

![zeropt](https://cloud.githubusercontent.com/assets/185007/11164720/ef5a388c-8aac-11e5-9268-61b8ac8462f1.png)

**Comment by jmeyers314** [comment]
Would it be worth using a different term than zero point for this?  Usually, an astronomical zero point corresponds to a magnitude at which the flux is 1 electron per second.  (For instance, http://www.stsci.edu/hst/acs/analysis/zeropoints).  Maybe "flux zeropoint" in contrast to magnitude zero point at the very least?

**Comment by dkirkby** [comment]
I wasn't really sure what "zero point" meant when I started using it here, but I guess the original zero point is Vega, and now it just means something that fixes the normalization of a photometric system.

The [DES SV photometry](https://cdcvs.fnal.gov/redmine/projects/des-sci-verification/wiki/Photometry) uses the notation `Zpt (mag)` for the AB magnitude corrsponding to 1 elec/sec and `Zpt (e-)` for the number of elec/sec that corresponds to AB=20 mag.

Josh's suggested "flux zero point" sounds like an improvement to me.  Of course, there is no substitute for actual equations to define your terms!
