### ISSUE TITLE
id -> galtileid?

### ISSUE THREAD

**Issue by jmeyers314** [DarkEnergyScienceCollaboration/WeakLensingDeblending#11]
Hi David,

I'm looking through some of this code to try and figure out why Ismael's getting weird results.  I came across this line: https://github.com/DarkEnergyScienceCollaboration/WeakLensingDeblending/blob/master/descwl/catalog.py#L87

I'm guessing this should be

```
if self.only_id and entry['galtileid'] not in self.only_id:
```

but wanted to make sure I'm interpreting your intentions right.  Can you confirm?

**Comment by dkirkby** [comment]
Yes!  (and the same two lines below).  I renamed 'id' to 'galtileid' at some point and obviously didn't test this option after the change.  Can you make a PR with just this fix or should I do it?
