### ISSUE TITLE
Reproduce numbers of https://arxiv.org/abs/0805.2366

### ISSUE THREAD

**Issue by fjaviersanchez** [DarkEnergyScienceCollaboration/WeakLensingDeblending#22]
I prepared a notebook in here:

https://gist.github.com/fjaviersanchez/28a2ebc0b22cc5d0b7fa76579a356a69

I computed the median 5-sigma depth (using sigma_grpf) and the MAD as its error. The numbers are compatible (the errors are quite large due to the size of the image).

@ dkirkby Should I push this notebook to the repo?

**Comment by dkirkby** [comment]
I think this should eventually be a cmd-line script, but let's keep it as a notebook for now.  Isn't `snr_iso` closer to how the 5-sigma depth is defined?

**Comment by fjaviersanchez** [comment]
Yes, you're right. That's closer to the point-source depth. I can make a cmd-line script. Should it read the band directly from the image or should we require it as an input?
