### ISSUE TITLE
Review LSST exposure times

### ISSUE THREAD

**Issue by fjaviersanchez** [DarkEnergyScienceCollaboration/WeakLensingDeblending#27]
Right now we have 6900s exposure times in all filters for LSST. Should we use the latest numbers in Ivezic et al (https://arxiv.org/abs/0805.2366)?

**Comment by dkirkby** [comment]
Yes 👍

**Comment by fjaviersanchez** [comment]
Updated in master. These are the new numbers:
u, g, r, i, z, y (seconds)
1680, 2400, 5520, 5520, 4800, 4800
