### ISSUE TITLE
more realistic PSFs from externally produced models

### ISSUE THREAD

**Issue by rmandelb** [DarkEnergyScienceCollaboration/WeakLensingDeblending#29]
A student working with me, Husni ( @hsnee ), would like to make it possible to use a more realistic PSF model with variation across the focal plane.  He is working on this on a branch in the repo called ```external_psf```.  Before surprising you with a pull request, I thought it might be worth us discussing how this will be done, in case you have suggestions for the cleanest way to incorporate this feature into the code.

Going through the code in https://github.com/LSSTDESC/WeakLensingDeblending/blob/master/descwl/survey.py , it became clear to us that for a given image, there's just a single PSF model defined using various input quantities for the FWHM, beta, and shape.

What Husni wants to do is provide a model that gives an image (like a NumPy array or galsim.Image or a galsim.InterpolatedImage) of the PSF model as a function of position within the image.  So there are a few questions:

1. Inputs: we could imagine adding a kwarg called ```external_psf``` that defaults to False.  It should either be False or it should be a callable routine that takes arguments for the focal plane (x, y) location to get the PSF image.  In the second case (pass name of callable routine),  all the PSF-related input kwargs would be ignored, while the first case (False) maintains the current behavior.  Does this sound reasonable or is there some other way that we should do this?

2. ```Survey.__init__``` internals: would have to be rearranged to either do what it currently does if ```external_psf=False```, or not do all the bits that calculate PSF moments if an external PSF model is passed in.

3. ```GalaxyRenderer```: needs to interact with ```Survey``` object to get the PSF model depending on the object position.

4. Analysis routines in ```analysis.py```: need to be updated to do the bookkeeping for each object potentially having a different PSF model

Does this make sense?  Any obvious show-stoppers?  Alternate ideas?

**Comment by fjaviersanchez** [comment]
@rmandelb I think that what you suggest makes sense. I think the best place to introduce this is `survey.py` where you can also add the `external_psf` argument. The main problem that I see is that when you call `survey.psf_model` you might need to include some position as argument as you mentioned but I think that's all. In `analysis.py` and `output.py` you also have to include information about the PSF. @dkirkby might have more suggestions :)

**Comment by dkirkby** [comment]
Welcome @hsnee!

This sounds like a useful feature and the general plan sounds good.  I was a bit confused about what the "image of the PSF model" represents: is it the PSF itself, or a numerical representation of how its parameters vary across the image?

A general issue here is that we have mostly focused on simulating a full-depth coadd in one shot, but this is a feature geared towards simulating single exposures (good!)  If you are planning to simulate multiple exposures under different observing conditions (sky level, seeing, extinction, airmass), another related feature we need is to sample these conditions correctly (e.g., using a table extracted from an OpSim run).

**Comment by rmandelb** [comment]
Hi @dkirkby - in the end we decided not to move forward with this right now, because of the need to address what happens with single-exposure PSF modeling errors as they get propagated into the full stack of images.  So, I am closing this issue.
