### ISSUE TITLE
grp covariances depending on simulation size??

### ISSUE THREAD

**Issue by fjaviersanchez** [DarkEnergyScienceCollaboration/WeakLensingDeblending#38]
@ismael2395 brought to my attention that when he does:

```
./simulate.py --catalog-name OneDegSq.fits --image-width 1800 --image-height 1800\
               --ra-center -0.05 --dec-center -0.45\
               --survey-name LSST --filter-band i --output-name demo2 --verbose
```
he gets different results for the group `402700140027` than when he runs:
```
./simulate.py --catalog-name OneDegSq.fits --image-width 600 --image-height 600\
               --ra-center -0.04160895 --dec-center -0.42082338888888887\
               --survey-name LSST --filter-band i --output-name demo3 --verbose
```
Even though that group is fully contained within the image width and height. This requires some follow-up investigation.
@ismael2395: Please, feel free to elaborate more on this and/or include any plots you find relevant.

**Comment by ismael-mendoza** [comment]
Thanks @fjaviersanchez for posting the issue. As Javier mentioned, the two simulate commands posted above both produce a stamp that completely contains the group `402700140027` (in both cases the table produced indicates that the `grp_size` is `77`)  but the grp fisher errors produced are different. One example of this is a galaxy with `db_id: 402700857466` which in `demo2` (output of first simulate command) has reasonable and small grp fisher errors (e.g. for `dg1_grp`) but in `demo3` the fisher errors for this galaxy are all `inf`. I should also mention that `demo3` is centered on this galaxy specifically. 

As we both understand the fisher calculation, we think that two different stamps that both contain the group should output the same fisher errors even if the stamp sizes are different?

**Comment by fjaviersanchez** [comment]
I am going to try to summarize the progress about this issue here:

1) We tried to switch from `np.linalg.inv` to a pseudoinverse method (in this case `np.linalg.pinv`).
2) It looks like this partially solves the problem. However, some checks about the pseudoinverse seem to fail (e.g., A A^+ A = A but A^+ A A^+ != A^+) and `np.diag(AA^+) != np.ones(A.shape[0])`
3) There are several ways to compute the pseudoinverse. More info [here](https://vene.ro/blog/inverses-pseudoinverses-numerical-issues-speed-symmetry.html).
4) More tests are needed to clarify which test is best (although, I'd say that `scipy.linalg.pinv` performs best).

**Comment by ismael-mendoza** [comment]
Some other (possibly) useful references for pinv vs. pinv2 vs np.pinv... 

- https://stackoverflow.com/questions/27775986/numpy-scipy-pinv-and-pinv2-behave-differently
- https://github.com/scipy/scipy/issues/8861
- https://stackoverflow.com/questions/13265299/the-difference-of-pseudo-inverse-between-scipy-and-numpy/13265930#13265930
- https://github.com/scipy/scipy/issues/4372

**Comment by ismael-mendoza** [comment]
After some discussion with @fjaviersanchez  and @burchat I believe I understand what was causing this issue and it is not really a bug in the code. I was looking at this paper https://arxiv.org/abs/gr-qc/0703086 (Use and Abuse of the Fisher Information Matrix in the Assessment of Gravitational-Wave Parameter-Estimation Prospects) and here is the relevant excerpt from it: 

> Taken at face value, this means that the Fisher-matrix results of Eqs. (24) and Eqs. (36) may be inaccurate to a 100% level if the components of the Fisher matrix are not known to a fractional accuracy better than $\kappa^{-1}(F)$ (pg. 12, first paragraph) 

where `\kappa^{-1}(F)` is the inverse condition number of the fisher matrix `F`. More intuitively, this means that if the condition number of the fisher matrix is large, small perturbations can have very large effect when trying to invert it. For the smaller of the patches above, where the fisher matrix is invertible including all of the galaxies (nothing is dropped), the condition number is of order of 1e22, which is way too large to trust.

Javier clarified to me that two different simulated patches will result in different `background` when calculating the fisher elements. I suspect that the background is not very different but even small variations are enough to change the fisher elements in a way that make such ill-conditioned Fisher matrix to go haywire. 

@fjaviersanchez hopefully this clarifies the issue and solves the mystery. I'm closing this issue now, but if there is something left to be addressed or that you wanted to add, please feel free to reopen or comment below. Thanks everyone for your help :)

**Comment by ismael-mendoza** [comment]
Description of what `background` refers to in the code by @fjaviersanchez in case it's useful in the future, 
>The sky level is the same in both cases. However, at the time of normalizing the fisher images, we use a cutout of what we call “background image” in the code, i.e., the survey image containing the pair of sources under consideration. The size of this image depends on the overlap between the sources and the size of the survey image as set by the user. Changing the size  with the —image-width and —image-height parameters can change this “background image” and the normalization of the Fisher images bit. A way to check for this is executing the get_fisher_images method in analysis.py. More details can be found in the code: https://github.com/LSSTDESC/WeakLensingDeblending/blob/c79533164e3a15d37d0a42b57aa336a118330e17/descwl/analysis.py#L269
