### ISSUE TITLE
Adding Fisher bias calculation. 

### ISSUE THREAD

**Issue by ismael-mendoza** [DarkEnergyScienceCollaboration/WeakLensingDeblending#9]
Adding bias calculation using the Fisher Formalism to the package will be useful. To calculate the biases it is necessary to first obtain the second partial derivatives of the galaxy with respect to its parameters. 

An idea is to calculate the second partials in render.py like the first partials and store all the partials together in the datacubes (set an optional flag because this will potentially make the fits file become very big). Then we would need to add the corresponding functions in analysis.py to get the biases from the second partials. Bias images can also be displayed by adding the corresponding functions in fisher.py

**Comment by dkirkby** [comment]
This sounds useful.  Have you thought about how you want to calculate the 2nd derivatives?  I used one-sided finite differences for the 1st derivatives, to reduce the number of different GalSim renderings required.  The 2nd derivative could re-use the images already rendered for the first derivative.

**Comment by dkirkby** [comment]
@ismael2395 I would like to add you to the list of collaborators for this repo, but I suspect you need to join the DarkEnergyScienceCollaboration team first.

**Comment by drphilmarshall** [comment]
@dkirkby - this project is public, so @ismael2395 can just fork the repo
and submit a pull request. This will also put him on the watch list as
well, so he'll get all the email notifications.

**Comment by ismael-mendoza** [comment]
Thanks for the clarification @drphilmarshall , I already forked the repo and will do work on it @dkirkby . That is a great idea @dkirkby ! Taking advantage of the images before would make it faster. Once I have a working implementation of this I will post it in this comment. -- actually in the bottom one.

**Comment by ismael-mendoza** [comment]
I looked through your code @dkirkby and noticed that you calculate your partial derivatives two-sidedly? (render.py, line244)  

```
        # Calculate partial derivative images, if requested.
        if not no_partials:
            for i,(pname,delta) in enumerate(variations):
                variation_stamp = (galaxy.renderer.draw(**{pname: +delta}).copy() - 
                    galaxy.renderer.draw(**{pname: -delta}))
                datacube[i+1] = variation_stamp.array/(2*delta)
```

So after some calculations I noticed that with a 6 parameter galaxy, doing one-sided second partials for the galaxies would require only 16 total galsim draws and two-sided second partials would require 41 total draws (taking advantage of the images rendered in both cases before the second partials) 
I was thinking that for robustness sake it is still better to do two-sided derivatives, in any case a good idea would be to add  a command line argument like `no_second_partials` so the user can choose not to calculate second partials if he/she so desires.

**Comment by dkirkby** [comment]
Yes, it looks like you are right about the two-sided derivative.  It must a different project where I used one-sided partials.

Rather than 'no-second-partials' I would name your option something like 'no-bias', to emphasize what is actually calculated (rather than how).  If it turns out that the bias calculations slow down the analysis a lot, you should probably reverse the logic so they are disabled by default and something like 'calculate-bias' turns it on.

Note that the flux partials can probably be calculated analytically, so that should speed things up a bit.

**Comment by drphilmarshall** [comment]
PS. @dkirkby did you also try inviting Ismael to join a team with write
access to this repo? I think you should be able to. You have write access
through your membership of the WeakLensing team, but also admin access
through the Old Owners team, and its the latter that should work even if
the former does not. There is precedent for DESC repos having non DESC
members with write access - this conversation reminds me that this is
something that the publications committee shoudl write about in their
policy draft.

**Comment by dkirkby** [comment]
It looks like only the WeakLensing "Team Maintainers" (@mdschneider, @rmjarvis) can invite someone to join the team, and OldOwners is now a regular team with no associated admin access.

**Comment by drphilmarshall** [comment]
OK, good to know - thanks David!

**Comment by rmjarvis** [comment]
> It looks like only the WeakLensing "Team Maintainers" (@mdschneider, @rmjarvis) can invite someone to join the team, and OldOwners is now a regular team with no associated admin access.

Did you want me to add him?

Or, personally, I'd be perfectly happy to have more people be maintainers.  @drphilmarshall, Any problem with adding David as a maintainer.  Probably a few others as well I would imagine.  But David at least, since he's probably the most active WLer on the repo.

**Comment by drphilmarshall** [comment]
Done - @dkirkby is now a Weak Lensing team maintainer.

**Comment by dkirkby** [comment]
Thanks @drphilmarshall.  It turns out that I can only add existing DarkEnergyScienceCollaboration members, so Ismael will need to join the DESC github organization first.

**Comment by drphilmarshall** [comment]
Interesting! I just sent @ismael2395 an invitation to the organization. When he has accepted his invitation, maybe you could try altering his status to "Outside Collaborator"? Interested to know if Team Maintainers can do that. They _should_ be able to...

**Comment by dkirkby** [comment]
I am now declaring this issue closed - thanks for all the hard work @ismael2395 !

**Comment by ismael-mendoza** [comment]
Thanks for all your help @dkirkby! I am glad to have contributed to your package
